language: ruby
rvm:
- 2.4.1
cache: bundler
install: gem install jekyll
before_script:
- git clone https://github.com/szbpsz/text.git tmp
- cp -r tmp/* ./
- rm -r -f tmp
- bundle install
script: bundle exec jekyll build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  skip_cleanup: true
  provider: firebase
  project: szbpsz-d612a
  token:
    secure: s3wPJVIO6v0woUUGuyOXNrBca5GOJ5OGR8H/TrAAUgwoU5v0suHCCmzvSjRqy6vPXTGJuqntmyeC9eX0gBmMzQMlyWB+QLqmMbBqiXaXVmx8ASMlMCcR/ojNVRJoS2ZODN7okN0kyBRHsppBFENYngfFOfbDZRDZvJNLswQ4eCjDU5hjs5ELgyfzYIjJcn+uo0AApJfRHHcn+SBuNvVCQ2wnGCczkNGwhbsXQbqcP2h0s4Oe3X25QefO0Y3yeQHPCmPHF9SPZd1o9cac6MDlWwTtnsYTxG+ht91k/71mLtg+U30Fdm0xgqyOnl6xkOOce94aHctl0urG+wC9Tl1d+BwFyjPd7OeA0NWsjznN1r54+FBWGNcviQGX735zcJcVTK4tXavLFdXsjQtjyLTr8gYnYD95QCnWxjWQdaM6XRVgqBq+hbRsY6Jf1aIB/W8krHUSeXkwhYQnelBODmBay9pRgPajHzEJIFadI3bbdl+oW/SU6bo0B3IhUajC8qur+wPMGUPoVJ0Bgw+Mw4PuwNqL1SAU0TeezJEqkIalvxXmE7cAHZD/YKRQr3M7uXhV1yfZeiaIKYpPSl/i0rD7eQy/KSr8pQX+sy2CrFGfJ29bvBCpM48LawEGtyFRKJ48oOx4QtpKCycEa7B4OOM/+WTkFGvfWMUX+kTleAPCsc0=
notifications:
  email:
    recipients:
    - nagy.gergely14@gmail.com
